import { defineStore } from "pinia";

export const useAdminClaimStore = defineStore("adminClaim", {
  state: () => ({
    claims: [],
  }),

  getters: {
    totalCount: (state) => state.claims.length,

    approvedCount: (state) =>
      state.claims.filter((claim) => claim.Status === "Approved").length,

    rejectedCount: (state) =>
      state.claims.filter((claim) => claim.Status === "Rejected").length,

    getApproved: (state) => {
      return state.claims.filter(
        (claim) => claim.Status?.toLowerCase() === "approved",
      );
    },

    getRejected: (state) => {
      return state.claims.filter(
        (claim) => claim.Status?.toLowerCase() === "rejected",
      );
    },
  },

  actions: {
    async initClaims() {
      this.claims = [
        {
          id: "GMD2039",
          Name: "Lindsay Walton",
          title: "Front-End Developer",
          email: "lindsay.walton@example.com",
          Date: "29/05/2025",
          Total: "85.00",
          Status: "Rejected",
          remark: "Claim for essential software and professional development.",
          IsAnomaly: false,
          IsFraud: false,
          items: [
            {
              category: "Software License",
              date: "29/05/2025",
              merchantName: "Software Central",
              merchantAddress: "Level 2, Digital Mall, Petaling Jaya, Selangor",
              description: "Vue.js Development Tools Subscription",
              quantity: 1,
              unitPrice: 50.0,
            },
            {
              category: "Online Course",
              date: "29/05/2025",
              merchantName: "CodeAcademy Malaysia",
              merchantAddress: "Unit 10, Jaya One, Petaling Jaya, Selangor",
              description: "Advanced JavaScript & Vue.js Course",
              quantity: 1,
              unitPrice: 35.0,
            },
          ],
        },
        {
          id: "GMD2040",
          Name: "Alex Chen",
          title: "UX Designer",
          email: "alex.chen@example.com",
          Date: "30/05/2025",
          Total: "120.00",
          Status: "Pending",
          remark: "Expenses for improving design workflow and ergonomics.",
          IsAnomaly: true,
          IsFraud: false,
          items: [
            {
              category: "Design Software Subscription",
              date: "30/05/2025",
              merchantName: "Creative Suite MY",
              merchantAddress: "Menara TM, Jalan Pantai Baharu, Kuala Lumpur",
              description: "Adobe Creative Cloud Annual Plan",
              quantity: 1,
              unitPrice: 70.0,
            },
            {
              category: "Hardware",
              date: "30/05/2025",
              merchantName: "All IT Hypermarket",
              merchantAddress:
                "Low Yat Plaza, Jalan Bukit Bintang, Kuala Lumpur",
              description: "Logitech MX Master 3S Ergonomic Mouse",
              quantity: 1,
              unitPrice: 50.0,
            },
          ],
        },
        {
          id: "GMD2041",
          Name: "Sarah Johnson",
          title: "Marketing Specialist",
          email: "sarah.j@example.com",
          Date: "31/05/2025",
          Total: "65.00",
          Status: "Rejected",
          remark: "Funding for ongoing digital marketing initiatives.",
          IsAnomaly: false,
          IsFraud: true,
          items: [
            {
              category: "Advertising",
              date: "31/05/2025",
              merchantName: "Digital Marketing Agency (Local)",
              merchantAddress: "Level 5, The Gardens Mid Valley, Kuala Lumpur",
              description: "Social Media Ad Campaign - Q2",
              quantity: 1,
              unitPrice: 65.0,
            },
          ],
        },
        {
          id: "GMD2042",
          Name: "Michael Brown",
          title: "Graphic Designer",
          email: "michael.b@example.com",
          Date: "01/06/2025",
          Total: "45.00",
          Status: "Approved",
          remark: "Essential supplies for graphic design work.",
          IsAnomaly: false,
          IsFraud: false,
          items: [
            {
              category: "Subscription",
              date: "01/06/2025",
              merchantName: "Creative Stock MY",
              merchantAddress: "Online Service (Based in Malaysia)",
              description: "Local Stock Photo & Vector Subscription",
              quantity: 1,
              unitPrice: 25.0,
            },
            {
              category: "Supplies",
              date: "01/06/2025",
              merchantName: "CzipLee",
              merchantAddress: "1 Jalan Telawi 3, Bangsar, Kuala Lumpur",
              description: "Wacom Pen Nibs (Pack of 5)",
              quantity: 1,
              unitPrice: 20.0,
            },
          ],
        },
        {
          id: "GMD2043",
          Name: "Emily Wilson",
          title: "Content Writer",
          email: "emily.w@example.com",
          Date: "02/06/2025",
          Total: "90.00",
          Status: "Pending",
          remark: "Resources for content quality and research.",
          IsAnomaly: true,
          IsFraud: false,
          items: [
            {
              category: "Software",
              date: "02/06/2025",
              merchantName: "Language AI Solutions",
              merchantAddress: "Menara Axis, Petaling Jaya, Selangor",
              description: "Premium Grammar & Plagiarism Checker",
              quantity: 1,
              unitPrice: 40.0,
            },
            {
              category: "Book",
              date: "02/06/2025",
              merchantName: "MPH Bookstores",
              merchantAddress: "Mid Valley Megamall, Kuala Lumpur",
              description: "Essential Guide to Content Marketing",
              quantity: 1,
              unitPrice: 50.0,
            },
          ],
        },
        {
          id: "GMD2044",
          Name: "David Lee",
          title: "Photographer",
          email: "david.lee@example.com",
          Date: "03/06/2025",
          Total: "150.00",
          Status: "Approved",
          remark: "Equipment and studio rental for professional shoots.",
          IsAnomaly: false,
          IsFraud: false,
          items: [
            {
              category: "Equipment",
              date: "03/06/2025",
              merchantName: "Foto Shangri-La",
              merchantAddress: "Jalan Pudu, Kuala Lumpur",
              description: "Camera Lens Cleaning Kit",
              quantity: 1,
              unitPrice: 100.0,
            },
            {
              category: "Rental",
              date: "03/06/2025",
              merchantName: "Studio Rente",
              merchantAddress: "Sunway Damansara, Petaling Jaya, Selangor",
              description: "Photography Studio Rental - Half Day",
              quantity: 1,
              unitPrice: 50.0,
            },
          ],
        },
        {
          id: "GMD2045",
          Name: "Jessica Tan",
          title: "Social Media Manager",
          email: "jessica.t@example.com",
          Date: "04/06/2025",
          Total: "200.00",
          Status: "Rejected",
          remark: "Tools and ad spend for social media campaigns.",
          IsAnomaly: true,
          IsFraud: true,
          items: [
            {
              category: "Software",
              date: "04/06/2025",
              merchantName: "SocialReach MY",
              merchantAddress: "Online Service (Kuala Lumpur Office)",
              description: "Social Media Management Platform Subscription",
              quantity: 1,
              unitPrice: 120.0,
            },
            {
              category: "Advertising",
              date: "04/06/2025",
              merchantName: "Facebook / Instagram Ads Malaysia",
              merchantAddress: "Level 10, TRX Exchange 106, Kuala Lumpur",
              description: "Instagram Ad Campaign Budget",
              quantity: 1,
              unitPrice: 80.0,
            },
          ],
        },
        {
          id: "GMD2046",
          Name: "Ryan Wong",
          title: "Video Editor",
          email: "ryan.w@example.com",
          Date: "05/06/2025",
          Total: "350.00",
          Status: "Pending",
          remark: "Claim for video production software and assets.",
          IsAnomaly: false,
          IsFraud: false,
          items: [
            {
              category: "Software",
              date: "05/06/2025",
              merchantName: "ProEdit Solutions",
              merchantAddress: "Cyberjaya City Centre, Cyberjaya, Selangor",
              description: "Video Editing Software License (Annual)",
              quantity: 1,
              unitPrice: 250.0,
            },
            {
              category: "Subscription",
              date: "05/06/2025",
              merchantName: "Malay Stock Footage",
              merchantAddress: "Online Platform (Based in KL)",
              description: "Premium Stock Footage Subscription",
              quantity: 1,
              unitPrice: 100.0,
            },
          ],
        },
        {
          id: "GMD2047",
          Name: "Amanda Lim",
          title: "Event Coordinator",
          email: "amanda.l@example.com",
          Date: "06/06/2025",
          Total: "500.00",
          Status: "Approved",
          remark: "Deposits for upcoming corporate event.",
          IsAnomaly: true,
          IsFraud: false,
          items: [
            {
              category: "Venue",
              date: "06/06/2025",
              merchantName: "KL Convention Centre",
              merchantAddress:
                "Jalan Pinang, Kuala Lumpur City Centre, Kuala Lumpur",
              description: "Exhibition Hall Booking Deposit",
              quantity: 1,
              unitPrice: 300.0,
            },
            {
              category: "Catering",
              date: "06/06/2025",
              merchantName: "Big Plate Catering",
              merchantAddress: "Jalan PJS 11/15, Bandar Sunway, Selangor",
              description: "Event Catering Service Deposit",
              quantity: 1,
              unitPrice: 200.0,
            },
          ],
        },
        {
          id: "GMD2048",
          Name: "Daniel Koh",
          title: "Print Specialist",
          email: "daniel.k@example.com",
          Date: "07/06/2025",
          Total: "80.00",
          Status: "Pending",
          remark: "Replenishing printing supplies for the office.",
          IsAnomaly: false,
          IsFraud: true,
          items: [
            {
              category: "Supplies",
              date: "07/06/2025",
              merchantName: "MR. D.I.Y.",
              merchantAddress:
                "Various outlets, e.g., Mid Valley Megamall, Kuala Lumpur",
              description: "A4 Printing Paper (10 reams)",
              quantity: 10,
              unitPrice: 3.0,
            },
            {
              category: "Supplies",
              date: "07/06/2025",
              merchantName: "Inkjet Refill Store",
              merchantAddress: "Digital Mall, Petaling Jaya, Selangor",
              description: "Compatible Ink Cartridges (Multi-pack)",
              quantity: 2,
              unitPrice: 25.0,
            },
          ],
        },
        {
          id: "GMD2049",
          Name: "Michelle Ho",
          title: "Brand Strategist",
          email: "michelle.h@example.com",
          Date: "08/06/2025",
          Total: "600.00",
          Status: "Approved",
          remark: "Investment in market intelligence and team development.",
          IsAnomaly: false,
          IsFraud: false,
          items: [
            {
              category: "Research",
              date: "08/06/2025",
              merchantName: "Fusion Analytics MY",
              merchantAddress: "The Vertical, Bangsar South, Kuala Lumpur",
              description: "Malaysian Consumer Market Report Q1 2025",
              quantity: 1,
              unitPrice: 400.0,
            },
            {
              category: "Workshop",
              date: "08/06/2025",
              merchantName: "Local Branding Experts",
              merchantAddress: "Co-Labs Coworking, The Starling, Petaling Jaya",
              description: "Effective Brand Communication Workshop",
              quantity: 1,
              unitPrice: 200.0,
            },
          ],
        },
      ];
    },

    async initStore() {
      this.initClaims();
    },
  },
});
