/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/claim/all': RouteRecordInfo<'/admin/claim/all', '/admin/claim/all', Record<never, never>, Record<never, never>>,
    '/admin/claim/review/[id]': RouteRecordInfo<'/admin/claim/review/[id]', '/admin/claim/review/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/admin/dashboard': RouteRecordInfo<'/admin/dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/policy/edit': RouteRecordInfo<'/admin/policy/edit', '/admin/policy/edit', Record<never, never>, Record<never, never>>,
    '/admin/policy/upload': RouteRecordInfo<'/admin/policy/upload', '/admin/policy/upload', Record<never, never>, Record<never, never>>,
    '/ask-claimsy': RouteRecordInfo<'/ask-claimsy', '/ask-claimsy', Record<never, never>, Record<never, never>>,
    '/employee/claim/all': RouteRecordInfo<'/employee/claim/all', '/employee/claim/all', Record<never, never>, Record<never, never>>,
    '/employee/claim/approved': RouteRecordInfo<'/employee/claim/approved', '/employee/claim/approved', Record<never, never>, Record<never, never>>,
    '/employee/claim/edit': RouteRecordInfo<'/employee/claim/edit', '/employee/claim/edit', Record<never, never>, Record<never, never>>,
    '/employee/claim/expenses': RouteRecordInfo<'/employee/claim/expenses', '/employee/claim/expenses', Record<never, never>, Record<never, never>>,
    '/employee/claim/rejected': RouteRecordInfo<'/employee/claim/rejected', '/employee/claim/rejected', Record<never, never>, Record<never, never>>,
    '/employee/claim/upload': RouteRecordInfo<'/employee/claim/upload', '/employee/claim/upload', Record<never, never>, Record<never, never>>,
    '/employee/rewards': RouteRecordInfo<'/employee/rewards', '/employee/rewards', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
  }
}
