/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarInput: typeof import('./components/form/CalendarInput.vue')['default']
    Chatbot: typeof import('./components/Chatbot.vue')['default']
    ClaimsCard: typeof import('./components/ClaimsCard.vue')['default']
    ClaimsTab: typeof import('./components/ClaimsTab.vue')['default']
    DropdownInput: typeof import('./components/form/DropdownInput.vue')['default']
    Navbar: typeof import('./components/navbar/index.vue')['default']
    NavLink: typeof import('./components/navbar/NavLink.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./components/tab.vue')['default']
    TextInput: typeof import('./components/form/TextInput.vue')['default']
    UploadCard: typeof import('./components/UploadCard.vue')['default']
  }
}
